### ISSUE TITLE
是否可以优化Loading checkpoint shards:

### ISSUE THREAD

**Issue by xueqing0622** [smthemex/ComfyUI_MS_Diffusion#1]
Loading checkpoint shards: 好浪费时间
可以参照这里
https://github.com/kijai/ComfyUI-KwaiKolorsWrapper/issues/6

**Comment by xueqing0622** [comment]
没事生图时间加起来都没有Loading checkpoint shards:久
![image](https://github.com/smthemex/ComfyUI_MS_Diffusion/assets/114840118/d7d418cb-c534-4ae4-b84e-cb8aab80a517)

**Comment by smthemex** [comment]
这个模型检查已经修正，改成false，取消了模型的检查

**Comment by xueqing0622** [comment]
谢谢！
