### ISSUE TITLE
guidance_list这个参数如何设置?

### ISSUE THREAD

**Issue by libaiabcd** [smthemex/ComfyUI_MS_Diffusion#3]
guidance_list这个参数我有三张图设置为:0., 0.25, 0.4, 0.75;0., 0.25, 0.4, 0.75;0., 0.25, 0.4, 0.75.    
0.   0.25  0.4  0.75 的作用分别是什么?
求教求教

**Comment by smthemex** [comment]
0.0,0.25,04,0.75 是在1.0*1.0的框内，画一个box，这个0.0,0.25,04,0.75对应的是这个BOX的坐标，如果你选择3张图，想3张图都在一个box内，可以保持3个坐标一样，如果想1个在上，1个在下，就要调整box的纵坐标参数。我还没有测试他们的坐标是以世界坐标（0.0是左下角），还是像素坐标（0.0）是左上角来计算的。
